// Auto-generated by scraper
export interface SpecialEventCardProps {
  title: string;
  dateRange: string;
  imageUrl: string;
  readMoreUrl?: string;
  location: string;
}

export const specialSpots: Record<string, SpecialEventCardProps[]> = {
  "GrossmanGalleryB101": [
    {
      "title": "How do you throw a brick through the window… Public Reception",
      "dateRange": "Sep 4,  6 –  8pm",
      "location": "Grossman Gallery + Anderson Auditorium, SMFA at Tufts (230 Fenway)",
      "imageUrl": "https://d1djpsj9eoa7wx.cloudfront.net/api/file/6AYmTtELSSmTPDLAqgFE/convert",
      "readMoreUrl": "https://artgalleries.tufts.edu/events/226-how-do-you-throw-a-brick-through-the-window-public-reception"
    }
  ],
  "AndersonAuditoriumB105": [
    {
      "title": "How do you throw a brick through the window… Public Reception",
      "dateRange": "Sep 4,  6 –  8pm",
      "location": "Grossman Gallery + Anderson Auditorium, SMFA at Tufts (230 Fenway)",
      "imageUrl": "https://d1djpsj9eoa7wx.cloudfront.net/api/file/6AYmTtELSSmTPDLAqgFE/convert",
      "readMoreUrl": "https://artgalleries.tufts.edu/events/226-how-do-you-throw-a-brick-through-the-window-public-reception"
    },
    {
      "title": "Jeffrey Meris Artist Lecture: “I. Held. Up”",
      "dateRange": "Sep 5, 12pm– 1:30am",
      "location": "Anderson Auditorium | SMFA at Tufts, Boston",
      "imageUrl": "https://d1djpsj9eoa7wx.cloudfront.net/api/file/ge2RYox1SW9hXVDUxZBN/convert",
      "readMoreUrl": "https://artgalleries.tufts.edu/events/228-jeffrey-meris-artist-lecture-i-held-up"
    },
    {
      "title": "Beckwith Lecture: Johanna Hedva",
      "dateRange": "Oct 9,  6 –  8pm",
      "location": "Anderson Auditorium | SMFA at Tufts, Boston",
      "imageUrl": "https://d1djpsj9eoa7wx.cloudfront.net/api/file/hm3KjXcWRMWLXdNRgvZU/convert",
      "readMoreUrl": "https://artgalleries.tufts.edu/events/230-beckwith-lecture-johanna-hedva"
    },
    {
      "title": "Disability Culture Now: A Panel with Emily Watlington & Jeff Kasper",
      "dateRange": "Oct 28,  6 –  8pm",
      "location": "Anderson Auditorium | SMFA at Tufts, Boston",
      "imageUrl": "https://d1djpsj9eoa7wx.cloudfront.net/api/file/ytb8wTvOQ6CpET7QCrNP/convert",
      "readMoreUrl": "https://artgalleries.tufts.edu/events/227-disability-culture-now-a-panel-with-emily-watlington-jeff-kasper"
    }
  ]
};
